spring.application.name=usuarios-service

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/uajs_smart_campus
spring.datasource.username=root
spring.datasource.password=progamer2004

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=UAJS-SMART-CAMPUS-SECRET-KEY-2026-DEVELOPMENT-ONLY-123456789
jwt.expiration=86400000